-- One-time backfill: mark every post published before the notify feature
-- shipped as already notified, so the first workflow run emails nobody about
-- old content. Generated from src/content/blog on 2026-09-17.
-- Apply once: wrangler d1 execute francisroylilly --remote --file=db/d1-backfill-post-notifications.sql
INSERT OR IGNORE INTO PostNotification (postSlug, notifiedAt) VALUES
  ('2026-09-09-gods-perfect-timing', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-1-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-10-2026', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-11-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-13-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-16-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-19-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-2-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-2-pm-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-20-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-21-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-23-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-24-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-29-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-3-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-4-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-5-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-5-pm-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-7-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('april-9-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('august-12-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('december-16-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('february-9-2026', CAST(strftime('%s', 'now') AS INTEGER)),
  ('july-12-2026', CAST(strftime('%s', 'now') AS INTEGER)),
  ('july-8-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('june-19-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('june-29-2026', CAST(strftime('%s', 'now') AS INTEGER)),
  ('may-12-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('may-16-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('may-20-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('may-24-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('may-31-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('may-4-2026', CAST(strftime('%s', 'now') AS INTEGER)),
  ('may-5-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('october-24-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('september-7-2025', CAST(strftime('%s', 'now') AS INTEGER)),
  ('september-9-2025', CAST(strftime('%s', 'now') AS INTEGER));
